Algoritmo "Ex5"
// Disciplina  :  [ALGORITMOS E PROGRAMAÇÃO]
// Professor   : Nelson Paz
// Descrição   : "Exercicio 5"
// Autor(a)    : Kauã Felipe da Silva Jenior
// Data atual  : 04/03/2024
Var
// Seção de Declarações das variáveis 
 Num,Sucessor:Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreva ("Informe um numero:")
Leia (Num)
Sucessor<- Num + 1
escreval("O sucessor de", Num, " é:", Sucessor)

Fimalgoritmo