Algoritmo "ex8"
// Disciplina   : [Algoritimos e Programação]
// Professor   : Nelson Paz 
// Descrição   : ex8
// Autor(a)    : Kauã Felipe da Silva Jenior
// Data atual  : 11/03/2024
Var
// Seção de Declarações das variáveis 
  F: inteiro;
  conversao: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Informe a temperatura em Fahrenheit")
   leia(F)
   Conversao <- (F - 32) / 1.8
   Escreval("O grau em Celsius é: ", Conversao)

Fimalgoritmo